# Generated by Django 2.2.16 on 2020-09-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_store_credit_card"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.CharField(max_length=256)),
            ],
        ),
    ]
