# Generated by Django 2.2.16 on 2020-09-14 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200914_2257"),
        ("users", "0002_auto_20200914_2235"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit_card",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="homepage",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_homepage",
                to="home.HomePage",
            ),
        ),
    ]
